name: PR Review + Claude Mentions

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  # -----------------------
  # A. PR 자동 리뷰 (track_progress)
  # -----------------------
  auto-review-with-tracking:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: PR Review with Progress Tracking
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # 진행 상황 체크박스 코멘트 자동 생성/갱신
          track_progress: true

          # 리뷰에 필요한 툴 허용
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"

  # -----------------------
  # B. @claude 멘션 기반 수동 리뷰
  # -----------------------
  claude-on-mention:
    if: |
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && github.event.review != null && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code on mention
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
